### ISSUE TITLE
Russian encoding in game was broken

### ISSUE THREAD

**Issue by akazakou** [dragouf/Democracy3LanguageSelector#2]
When i apply the new translation on Russina language, i have broken encoding symbols.

![screenshot](https://cloud.githubusercontent.com/assets/326397/8147915/4cf84fbe-128b-11e5-8c64-2bce533a2cee.png)

**Comment by dragouf** [comment]
Sorry I know. Game developer said me he would add cyrillic support if the translation is done but he never did. I can't change that. It's not a bug related to this tool.

**Comment by akazakou** [comment]
But what problem in? Can you explain that, maybe i can find some solution without developers?

**Comment by dragouf** [comment]
It's just that the game can't display character other than latin alphabet. but since I don't know how developer made the game I don't know more about it. Perhaps you can try to contact him.
